class MarbleRunner {
    public static void main(String[] args) {
        System.out.println("Main Started - Marble Data");

        Marble marble1 = new Marble();
        marble1.color = "Blue";
        marble1.pattern = "Swirl";
        marble1.diameterCm = 1.6;
        marble1.material = "Glass";
        marble1.weightGrams = 5.2;
        marble1.isRare = false;
        System.out.println("Color: " + marble1.color);
        System.out.println("Pattern: " + marble1.pattern);
        System.out.println("Diameter (cm): " + marble1.diameterCm);
        System.out.println("Material: " + marble1.material);
        System.out.println("Weight (grams): " + marble1.weightGrams);
        System.out.println("Is Rare: " + marble1.isRare);
        System.out.println();

        Marble marble2 = new Marble();
        marble2.color = "Green";
        marble2.pattern = "Solid";
        marble2.diameterCm = 1.5;
        marble2.material = "Glass";
        marble2.weightGrams = 4.8;
        marble2.isRare = false;
        System.out.println("Color: " + marble2.color);
        System.out.println("Pattern: " + marble2.pattern);
        System.out.println("Diameter (cm): " + marble2.diameterCm);
        System.out.println("Material: " + marble2.material);
        System.out.println("Weight (grams): " + marble2.weightGrams);
        System.out.println("Is Rare: " + marble2.isRare);
        System.out.println();

        Marble marble3 = new Marble();
        marble3.color = "Red";
        marble3.pattern = "Speckled";
        marble3.diameterCm = 1.8;
        marble3.material = "Clay";
        marble3.weightGrams = 6.0;
        marble3.isRare = false;
        System.out.println("Color: " + marble3.color);
        System.out.println("Pattern: " + marble3.pattern);
        System.out.println("Diameter (cm): " + marble3.diameterCm);
        System.out.println("Material: " + marble3.material);
        System.out.println("Weight (grams): " + marble3.weightGrams);
        System.out.println("Is Rare: " + marble3.isRare);
        System.out.println();

        Marble marble4 = new Marble();
        marble4.color = "Yellow";
        marble4.pattern = "Cat's Eye";
        marble4.diameterCm = 1.7;
        marble4.material = "Glass";
        marble4.weightGrams = 5.5;
        marble4.isRare = false;
        System.out.println("Color: " + marble4.color);
        System.out.println("Pattern: " + marble4.pattern);
        System.out.println("Diameter (cm): " + marble4.diameterCm);
        System.out.println("Material: " + marble4.material);
        System.out.println("Weight (grams): " + marble4.weightGrams);
        System.out.println("Is Rare: " + marble4.isRare);
        System.out.println();

        Marble marble5 = new Marble();
        marble5.color = "Black";
        marble5.pattern = "Solid";
        marble5.diameterCm = 2.0;
        marble5.material = "Steel";
        marble5.weightGrams = 15.0;
        marble5.isRare = true;
        System.out.println("Color: " + marble5.color);
        System.out.println("Pattern: " + marble5.pattern);
        System.out.println("Diameter (cm): " + marble5.diameterCm);
        System.out.println("Material: " + marble5.material);
        System.out.println("Weight (grams): " + marble5.weightGrams);
        System.out.println("Is Rare: " + marble5.isRare);
        System.out.println();

        Marble marble6 = new Marble();
        marble6.color = "Orange";
        marble6.pattern = "Swirl";
        marble6.diameterCm = 1.6;
        marble6.material = "Glass";
        marble6.weightGrams = 5.0;
        marble6.isRare = false;
        System.out.println("Color: " + marble6.color);
        System.out.println("Pattern: " + marble6.pattern);
        System.out.println("Diameter (cm): " + marble6.diameterCm);
        System.out.println("Material: " + marble6.material);
        System.out.println("Weight (grams): " + marble6.weightGrams);
        System.out.println("Is Rare: " + marble6.isRare);
        System.out.println();

        Marble marble7 = new Marble();
        marble7.color = "Purple";
        marble7.pattern = "Solid";
        marble7.diameterCm = 1.5;
        marble7.material = "Glass";
        marble7.weightGrams = 4.9;
        marble7.isRare = false;
        System.out.println("Color: " + marble7.color);
        System.out.println("Pattern: " + marble7.pattern);
        System.out.println("Diameter (cm): " + marble7.diameterCm);
        System.out.println("Material: " + marble7.material);
        System.out.println("Weight (grams): " + marble7.weightGrams);
        System.out.println("Is Rare: " + marble7.isRare);
        System.out.println();

        Marble marble8 = new Marble();
        marble8.color = "White";
        marble8.pattern = "Speckled";
        marble8.diameterCm = 1.7;
        marble8.material = "Clay";
        marble8.weightGrams = 5.8;
        marble8.isRare = false;
        System.out.println("Color: " + marble8.color);
        System.out.println("Pattern: " + marble8.pattern);
        System.out.println("Diameter (cm): " + marble8.diameterCm);
        System.out.println("Material: " + marble8.material);
        System.out.println("Weight (grams): " + marble8.weightGrams);
        System.out.println("Is Rare: " + marble8.isRare);
        System.out.println();

        Marble marble9 = new Marble();
        marble9.color = "Brown";
        marble9.pattern = "Cat's Eye";
        marble9.diameterCm = 1.6;
        marble9.material = "Glass";
        marble9.weightGrams = 5.3;
        marble9.isRare = false;
        System.out.println("Color: " + marble9.color);
        System.out.println("Pattern: " + marble9.pattern);
        System.out.println("Diameter (cm): " + marble9.diameterCm);
        System.out.println("Material: " + marble9.material);
        System.out.println("Weight (grams): " + marble9.weightGrams);
        System.out.println("Is Rare: " + marble9.isRare);
        System.out.println();

        Marble marble10 = new Marble();
        marble10.color = "Silver";
        marble10.pattern = "Solid";
        marble10.diameterCm = 1.9;
        marble10.material = "Steel";
        marble10.weightGrams = 12.0;
        marble10.isRare = true;
        System.out.println("Color: " + marble10.color);
        System.out.println("Pattern: " + marble10.pattern);
        System.out.println("Diameter (cm): " + marble10.diameterCm);
        System.out.println("Material: " + marble10.material);
        System.out.println("Weight (grams): " + marble10.weightGrams);
        System.out.println("Is Rare: " + marble10.isRare);
        System.out.println();

        Marble marble11 = new Marble();
        marble11.color = "Pink";
        marble11.pattern = "Swirl";
        marble11.diameterCm = 1.5;
        marble11.material = "Glass";
        marble11.weightGrams = 4.7;
        marble11.isRare = false;
        System.out.println("Color: " + marble11.color);
        System.out.println("Pattern: " + marble11.pattern);
        System.out.println("Diameter (cm): " + marble11.diameterCm);
        System.out.println("Material: " + marble11.material);
        System.out.println("Weight (grams): " + marble11.weightGrams);
        System.out.println("Is Rare: " + marble11.isRare);
        System.out.println();

        Marble marble12 = new Marble();
        marble12.color = "Gray";
        marble12.pattern = "Solid";
        marble12.diameterCm = 1.7;
        marble12.material = "Clay";
        marble12.weightGrams = 5.6;
        marble12.isRare = false;
        System.out.println("Color: " + marble12.color);
        System.out.println("Pattern: " + marble12.pattern);
        System.out.println("Diameter (cm): " + marble12.diameterCm);
        System.out.println("Material: " + marble12.material);
        System.out.println("Weight (grams): " + marble12.weightGrams);
        System.out.println("Is Rare: " + marble12.isRare);
        System.out.println();

        Marble marble13 = new Marble();
        marble13.color = "Cyan";
        marble13.pattern = "Speckled";
        marble13.diameterCm = 1.6;
        marble13.material = "Glass";
        marble13.weightGrams = 5.1;
        marble13.isRare = false;
        System.out.println("Color: " + marble13.color);
        System.out.println("Pattern: " + marble13.pattern);
        System.out.println("Diameter (cm): " + marble13.diameterCm);
        System.out.println("Material: " + marble13.material);
        System.out.println("Weight (grams): " + marble13.weightGrams);
        System.out.println("Is Rare: " + marble13.isRare);
        System.out.println();

        Marble marble14 = new Marble();
        marble14.color = "Magenta";
        marble14.pattern = "Cat's Eye";
        marble14.diameterCm = 1.8;
        marble14.material = "Glass";
        marble14.weightGrams = 5.9;
        marble14.isRare = false;
        System.out.println("Color: " + marble14.color);
        System.out.println("Pattern: " + marble14.pattern);
        System.out.println("Diameter (cm): " + marble14.diameterCm);
        System.out.println("Material: " + marble14.material);
        System.out.println("Weight (grams): " + marble14.weightGrams);
        System.out.println("Is Rare: " + marble14.isRare);
        System.out.println();

        Marble marble15 = new Marble();
        marble15.color = "Gold";
        marble15.pattern = "Solid";
        marble15.diameterCm = 2.1;
        marble15.material = "Steel";
        marble15.weightGrams = 18.0;
        marble15.isRare = true;
        System.out.println("Color: " + marble15.color);
        System.out.println("Pattern: " + marble15.pattern);
        System.out.println("Diameter (cm): " + marble15.diameterCm);
        System.out.println("Material: " + marble15.material);
        System.out.println("Weight (grams): " + marble15.weightGrams);
        System.out.println("Is Rare: " + marble15.isRare);
        System.out.println();

        Marble marble16 = new Marble();
        marble16.color = "Lime Green";
        marble16.pattern = "Swirl";
        marble16.diameterCm = 1.7;
        marble16.material = "Glass";
        marble16.weightGrams = 5.4;
        marble16.isRare = false;
        System.out.println("Color: " + marble16.color);
        System.out.println("Pattern: " + marble16.pattern);
        System.out.println("Diameter (cm): " + marble16.diameterCm);
        System.out.println("Material: " + marble16.material);
        System.out.println("Weight (grams): " + marble16.weightGrams);
        System.out.println("Is Rare: " + marble16.isRare);
        System.out.println();

        Marble marble17 = new Marble();
        marble17.color = "Dark Blue";
        marble17.pattern = "Solid";
        marble17.diameterCm = 1.8;
        marble17.material = "Glass";
        marble17.weightGrams = 5.7;
        marble17.isRare = false;
        System.out.println("Color: " + marble17.color);
        System.out.println("Pattern: " + marble17.pattern);
        System.out.println("Diameter (cm): " + marble17.diameterCm);
        System.out.println("Material: " + marble17.material);
        System.out.println("Weight (grams): " + marble17.weightGrams);
        System.out.println("Is Rare: " + marble17.isRare);
        System.out.println();

        Marble marble18 = new Marble();
        marble18.color = "Light Green";
        marble18.pattern = "Speckled";
        marble18.diameterCm = 1.5;
        marble18.material = "Clay";
        marble18.weightGrams = 4.9;
        marble18.isRare = false;
        System.out.println("Color: " + marble18.color);
        System.out.println("Pattern: " + marble18.pattern);
        System.out.println("Diameter (cm): " + marble18.diameterCm);
        System.out.println("Material: " + marble18.material);
        System.out.println("Weight (grams): " + marble18.weightGrams);
        System.out.println("Is Rare: " + marble18.isRare);
        System.out.println();

        Marble marble19 = new Marble();
        marble19.color = "Teal";
        marble19.pattern = "Cat's Eye";
        marble19.diameterCm = 1.7;
        marble19.material = "Glass";
        marble19.weightGrams = 5.4;
        marble19.isRare = false;
        System.out.println("Color: " + marble19.color);
        System.out.println("Pattern: " + marble19.pattern);
        System.out.println("Diameter (cm): " + marble19.diameterCm);
        System.out.println("Material: " + marble19.material);
        System.out.println("Weight (grams): " + marble19.weightGrams);
        System.out.println("Is Rare: " + marble19.isRare);
        System.out.println();

        Marble marble20 = new Marble();
        marble20.color = "Bronze";
        marble20.pattern = "Solid";
        marble20.diameterCm = 2.0;
        marble20.material = "Steel";
        marble20.weightGrams = 16.5;
        marble20.isRare = true;
        System.out.println("Color: " + marble20.color);
        System.out.println("Pattern: " + marble20.pattern);
        System.out.println("Diameter (cm): " + marble20.diameterCm);
        System.out.println("Material: " + marble20.material);
        System.out.println("Weight (grams): " + marble20.weightGrams);
        System.out.println("Is Rare: " + marble20.isRare);
        System.out.println();

        System.out.println("Main Ended - Marble Data Display Complete");
    }
}
