class Desktop {
    static String brand;
    static String model ;
    static String processor ;
    static String operatingSystem ;
    static String motherboard ;
    static int ramSizeGB;
    static int storageSizeGB ;
    static String storageType ;
    static String graphicsCard ;
    static int powerSupplyWatts ;
    static boolean hasWiFi;
    static boolean hasBluetooth ;
    static boolean hasOpticalDrive ;
    static int noOfUSBPorts ;
    static boolean hasHDMIPort;
    static String cabinetType ;
    static double weightKg ;
    static String color ;
    static int yearOfManufacture;
    static boolean isPreBuilt;

    public static void main(String[] args) {
        System.out.println("Brand: " + brand);
        System.out.println("Model: " + model);
        System.out.println("Processor: " + processor);
        System.out.println("Operating System: " + operatingSystem);
        System.out.println("Motherboard: " + motherboard);
        System.out.println("RAM Size (GB): " + ramSizeGB);
        System.out.println("Storage Size (GB): " + storageSizeGB);
        System.out.println("Storage Type: " + storageType);
        System.out.println("Graphics Card: " + graphicsCard);
        System.out.println("Power Supply (Watts): " + powerSupplyWatts);
        System.out.println("Has WiFi: " + hasWiFi);
        System.out.println("Has Bluetooth: " + hasBluetooth);
        System.out.println("Has Optical Drive: " + hasOpticalDrive);
        System.out.println("Number of USB Ports: " + noOfUSBPorts);
        System.out.println("Has HDMI Port: " + hasHDMIPort);
        System.out.println("Cabinet Type: " + cabinetType);
        System.out.println("Weight (kg): " + weightKg);
        System.out.println("Color: " + color);
        System.out.println("Year of Manufacture: " + yearOfManufacture);
        System.out.println("Is Pre-Built: " + isPreBuilt);
		
	brand = "Dell";
    model = "OptiPlex 7090";
    processor = "Intel Core i7 11th Gen";
    String operatingSystem = "Windows 11 Pro";
    String motherboard = "Dell OEM Intel Chipset";
    int ramSizeGB = 16;
    int storageSizeGB = 512;
    String storageType = "SSD";
    String graphicsCard = "NVIDIA GeForce GTX 1660";
    int powerSupplyWatts = 500;
    boolean hasWiFi = true;
    boolean hasBluetooth = true;
    boolean hasOpticalDrive = false;
    int noOfUSBPorts = 6;
    boolean hasHDMIPort = true;
    String cabinetType = "Mini Tower";
    double weightKg = 6.5;
    String color = "Black";
    int yearOfManufacture = 2023;
    boolean isPreBuilt = true;
	System.out.println("Brand: " + brand);
    System.out.println("Model: " + model);
    System.out.println("Processor: " + processor);
    System.out.println("Operating System: " + operatingSystem);
    System.out.println("Motherboard: " + motherboard);
    System.out.println("RAM Size (GB): " + ramSizeGB);
    System.out.println("Storage Size (GB): " + storageSizeGB);
    System.out.println("Storage Type: " + storageType);
    System.out.println("Graphics Card: " + graphicsCard);
    System.out.println("Power Supply (Watts): " + powerSupplyWatts);
	System.out.println("Has WiFi: " + hasWiFi);
	System.out.println("Has Bluetooth: " + hasBluetooth);
	System.out.println("Has Optical Drive: " + hasOpticalDrive);
	System.out.println("Number of USB Ports: " + noOfUSBPorts);
	System.out.println("Has HDMI Port: " + hasHDMIPort);
	System.out.println("Cabinet Type: " + cabinetType);        
	System.out.println("Weight (kg): " + weightKg);
	System.out.println("Color: " + color);
    System.out.println("Year of Manufacture: " + yearOfManufacture);
    System.out.println("Is Pre-Built: " + isPreBuilt);
    }
}
