class ShoppingMall {
    static String mallName;
    static String location ;
    static String owner ;
    static String openingDate ;
    static String architect;
    static int numberOfFloors;
    static int numberOfShops ;
    static int numberOfRestaurants ;
    static int numberOfEscalators ;
    static int numberOfParkingSlots ;
    static boolean hasMovieTheater;
    static boolean hasFoodCourt ;
    static boolean hasKidsPlayArea ;
    static boolean hasWiFi;
    static boolean hasSecuritySystem ;
    static double builtUpAreaInSqFt;
    static int dailyFootfall ;
    static boolean isPetFriendly ;
    static String contactNumber;
    static String website;

    public static void main(String[] args) {
        System.out.println("Mall Name: " + mallName);
        System.out.println("Location: " + location);
        System.out.println("Owner: " + owner);
        System.out.println("Opening Date: " + openingDate);
        System.out.println("Architect: " + architect);
        System.out.println("Number of Floors: " + numberOfFloors);
        System.out.println("Number of Shops: " + numberOfShops);
        System.out.println("Number of Restaurants: " + numberOfRestaurants);
        System.out.println("Number of Escalators: " + numberOfEscalators);
        System.out.println("Number of Parking Slots: " + numberOfParkingSlots);
        System.out.println("Has Movie Theater: " + hasMovieTheater);
        System.out.println("Has Food Court: " + hasFoodCourt);
        System.out.println("Has Kids Play Area: " + hasKidsPlayArea);
        System.out.println("Has WiFi: " + hasWiFi);
        System.out.println("Has Security System: " + hasSecuritySystem);
        System.out.println("Built-up Area (sq ft): " + builtUpAreaInSqFt);
        System.out.println("Daily Footfall: " + dailyFootfall);
        System.out.println("Is Pet Friendly: " + isPetFriendly);
        System.out.println("Contact Number: " + contactNumber);
        System.out.println("Website: " + website);
	 mallName = "Orion Mall";
     location = "Bangalore, Karnataka";
     owner = "Brigade Group";
     openingDate = "2012-08-26";
     architect = "HOK Architects";
     numberOfFloors = 4;
     numberOfShops = 300;
     numberOfRestaurants = 40;
     numberOfEscalators = 10;
     numberOfParkingSlots = 2000;
     hasMovieTheater = true;
     hasFoodCourt = true;
     hasKidsPlayArea = true;
     hasWiFi = true;
     hasSecuritySystem = true;
     builtUpAreaInSqFt = 850000.0;
     dailyFootfall = 20000;
     isPetFriendly = false;
     contactNumber = "080-12345678";
     website = "https://www.orionmall.com";
	 
	 System.out.println("Mall Name: " + mallName);
        System.out.println("Location: " + location);
        System.out.println("Owner: " + owner);
        System.out.println("Opening Date: " + openingDate);
        System.out.println("Architect: " + architect);
        System.out.println("Number of Floors: " + numberOfFloors);
        System.out.println("Number of Shops: " + numberOfShops);
        System.out.println("Number of Restaurants: " + numberOfRestaurants);
        System.out.println("Number of Escalators: " + numberOfEscalators);
        System.out.println("Number of Parking Slots: " + numberOfParkingSlots);
        System.out.println("Has Movie Theater: " + hasMovieTheater);
        System.out.println("Has Food Court: " + hasFoodCourt);
        System.out.println("Has Kids Play Area: " + hasKidsPlayArea);
        System.out.println("Has WiFi: " + hasWiFi);
        System.out.println("Has Security System: " + hasSecuritySystem);
        System.out.println("Built-up Area (sq ft): " + builtUpAreaInSqFt);
        System.out.println("Daily Footfall: " + dailyFootfall);
        System.out.println("Is Pet Friendly: " + isPetFriendly);
        System.out.println("Contact Number: " + contactNumber);
        System.out.println("Website: " + website);
    }
}
