class Stadium {
    static String stadiumName ;
    static String location;
    static String owner ;
    static String primarySport ;
    static String architect;
    static int seatingCapacity;
    static int numberOfEntrances ;
    static int numberOfVIPBoxes ;
    static int numberOfFoodStalls ;
    static int numberOfParkingSlots ;
    static boolean hasRoof ;
    static boolean hasFloodLights ;
    static boolean hasLEDScoreboard;
    static boolean hasPracticeGround;
    static boolean isAccessible;
    static int yearOpened ;
    static double areaInAcres ;
    static boolean hostsConcerts ;
    static boolean hasMediaRoom;
    static String contactEmail ;

    public static void main(String[] args) {
        System.out.println("Stadium Name: " + stadiumName);
        System.out.println("Location: " + location);
        System.out.println("Owner: " + owner);
        System.out.println("Primary Sport: " + primarySport);
        System.out.println("Architect: " + architect);
        System.out.println("Seating Capacity: " + seatingCapacity);
        System.out.println("Number of Entrances: " + numberOfEntrances);
        System.out.println("Number of VIP Boxes: " + numberOfVIPBoxes);
        System.out.println("Number of Food Stalls: " + numberOfFoodStalls);
        System.out.println("Number of Parking Slots: " + numberOfParkingSlots);
        System.out.println("Has Roof: " + hasRoof);
        System.out.println("Has Flood Lights: " + hasFloodLights);
        System.out.println("Has LED Scoreboard: " + hasLEDScoreboard);
        System.out.println("Has Practice Ground: " + hasPracticeGround);
        System.out.println("Is Accessible: " + isAccessible);
        System.out.println("Year Opened: " + yearOpened);
        System.out.println("Area (in acres): " + areaInAcres);
        System.out.println("Hosts Concerts: " + hostsConcerts);
        System.out.println("Has Media Room: " + hasMediaRoom);
        System.out.println("Contact Email: " + contactEmail);
		
		stadiumName = "jaharlal nehru stadium";
    location = "Shimoga, karnataka";
     owner = "Sports Authority of karnataka";
     primarySport = "Cricket";
     architect = "National Architects Ltd.";
     seatingCapacity = 7500;
     numberOfEntrances = 12;
     numberOfVIPBoxes = 20;
     numberOfFoodStalls = 30;
    numberOfParkingSlots = 1000;
     hasRoof = false;
     hasFloodLights = true;
     hasLEDScoreboard = true;
     hasPracticeGround = true;
     isAccessible = true;
     yearOpened = 2005;
     areaInAcres = 50.0;
     hostsConcerts = true;
     hasMediaRoom = true;
     String contactEmail = "info@nationalsportsarena.in";
	 System.out.println("Stadium Name: " + stadiumName);
        System.out.println("Location: " + location);
        System.out.println("Owner: " + owner);
        System.out.println("Primary Sport: " + primarySport);
        System.out.println("Architect: " + architect);
        System.out.println("Seating Capacity: " + seatingCapacity);
        System.out.println("Number of Entrances: " + numberOfEntrances);
        System.out.println("Number of VIP Boxes: " + numberOfVIPBoxes);
        System.out.println("Number of Food Stalls: " + numberOfFoodStalls);
        System.out.println("Number of Parking Slots: " + numberOfParkingSlots);
        System.out.println("Has Roof: " + hasRoof);
        System.out.println("Has Flood Lights: " + hasFloodLights);
        System.out.println("Has LED Scoreboard: " + hasLEDScoreboard);
        System.out.println("Has Practice Ground: " + hasPracticeGround);
        System.out.println("Is Accessible: " + isAccessible);
        System.out.println("Year Opened: " + yearOpened);
        System.out.println("Area (in acres): " + areaInAcres);
        System.out.println("Hosts Concerts: " + hostsConcerts);
        System.out.println("Has Media Room: " + hasMediaRoom);
        System.out.println("Contact Email: " + contactEmail);
    }
}
