class SwitchBoard {
    static String brandName ;
    static String modelNumber ;
    static String material;
    static String color ;
    static String boardType ;
    static int noOfSwitches ;
    static int noOfSockets ;
    static int noOfIndicators ;
    static int noOfFuses ;
    static int voltageRating ; 
    static double frequency ; 
    static boolean hasSurgeProtection ;
    static boolean isSmartEnabled ;
    static boolean isChildProof ;
    static boolean hasUSBPorts ;
    static int noOfUSBPorts ;
    static double maxCurrentCapacity; 
    static boolean hasMCB ;
    static String mountingType ;
    static boolean isWaterResistant;
    public static void main(String[] args) {
        System.out.println("Brand Name: " + brandName);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Material: " + material);
        System.out.println("Color: " + color);
        System.out.println("Board Type: " + boardType);
        System.out.println("Number of Switches: " + noOfSwitches);
        System.out.println("Number of Sockets: " + noOfSockets);
        System.out.println("Number of Indicators: " + noOfIndicators);
        System.out.println("Number of Fuses: " + noOfFuses);
        System.out.println("Voltage Rating: " + voltageRating + "V");
        System.out.println("Frequency: " + frequency + "Hz");
        System.out.println("Has Surge Protection: " + hasSurgeProtection);
        System.out.println("Smart Enabled: " + isSmartEnabled);
        System.out.println("Child Proof: " + isChildProof);
        System.out.println("Has USB Ports: " + hasUSBPorts);
        System.out.println("Number of USB Ports: " + noOfUSBPorts);
        System.out.println("Max Current Capacity: " + maxCurrentCapacity + "A");
        System.out.println("Has MCB: " + hasMCB);
        System.out.println("Mounting Type: " + mountingType);
        System.out.println("Water Resistant: " + isWaterResistant);
		
		 brandName = "GM";
    modelNumber = "LSB2025";
     material = "Polycarbonate";
     color = "puple";
     boardType = "Modular";
   noOfSwitches = 6;
     noOfSockets = 2;
     noOfIndicators = 1;
     noOfFuses = 1;
     voltageRating = 240; 
     frequency = 50.0; 
    hasSurgeProtection = true;
     isSmartEnabled = false;
     isChildProof = true;
     hasUSBPorts = true;
     noOfUSBPorts = 2;
    maxCurrentCapacity = 16.0; 
     hasMCB = true;
     mountingType = "Wall Mounted";
     isWaterResistant = false;
	 System.out.println("Brand Name: " + brandName);
        System.out.println("Model Number: " + modelNumber);
        System.out.println("Material: " + material);
        System.out.println("Color: " + color);
        System.out.println("Board Type: " + boardType);
        System.out.println("Number of Switches: " + noOfSwitches);
        System.out.println("Number of Sockets: " + noOfSockets);
        System.out.println("Number of Indicators: " + noOfIndicators);
        System.out.println("Number of Fuses: " + noOfFuses);
        System.out.println("Voltage Rating: " + voltageRating + "V");
        System.out.println("Frequency: " + frequency + "Hz");
        System.out.println("Has Surge Protection: " + hasSurgeProtection);
        System.out.println("Smart Enabled: " + isSmartEnabled);
        System.out.println("Child Proof: " + isChildProof);
        System.out.println("Has USB Ports: " + hasUSBPorts);
        System.out.println("Number of USB Ports: " + noOfUSBPorts);
        System.out.println("Max Current Capacity: " + maxCurrentCapacity + "A");
        System.out.println("Has MCB: " + hasMCB);
        System.out.println("Mounting Type: " + mountingType);
        System.out.println("Water Resistant: " + isWaterResistant);
		
    }
}
