class Temple {
    static String templeName;
    static String location ;
    static int noOfPillars ;
    static int noOfDoors ;
    static int noOfPriests ;
    static int yearEstablished ;
    static boolean isHeritageSite ;
    static double templeAreaInAcres ;
    static String deityName ;
    static boolean hasGarden;
    static int noOfSteps;
    static String architectureStyle ;
    static boolean hasParkingFacility ;
    static int dailyVisitors ;
    static boolean hasCanteen ;
    static String mainFestival ;
    static boolean isOpenOnHolidays ;
    static int noOfRoomsForPilgrims ;
    static String trustName ;
    static boolean hasLibrary ;

    public static void main(String temple[]) {
        System.out.println("Temple Name: " + templeName);
        System.out.println("Location: " + location);
        System.out.println("Number of Pillars: " + noOfPillars);
        System.out.println("Number of Doors: " + noOfDoors);
        System.out.println("Number of Priests: " + noOfPriests);
        System.out.println("Year Established: " + yearEstablished);
        System.out.println("Is Heritage Site: " + isHeritageSite);
        System.out.println("Temple Area in Acres: " + templeAreaInAcres);
        System.out.println("Deity Name: " + deityName);
        System.out.println("Has Garden: " + hasGarden);
        System.out.println("Number of Steps: " + noOfSteps);
        System.out.println("Architecture Style: " + architectureStyle);
        System.out.println("Has Parking Facility: " + hasParkingFacility);
        System.out.println("Daily Visitors: " + dailyVisitors);
        System.out.println("Has Canteen: " + hasCanteen);
        System.out.println("Main Festival: " + mainFestival);
        System.out.println("Is Open on Holidays: " + isOpenOnHolidays);
        System.out.println("Number of Rooms for Pilgrims: " + noOfRoomsForPilgrims);
        System.out.println("Trust Name: " + trustName);
        System.out.println("Has Library: " + hasLibrary);
		
	templeName = "Siddhivinayaka Temple";
    location = "Ganapatikatte";
    noOfPillars =8;
    noOfDoors = 3;
    noOfPriests = 5;
    yearEstablished = 1954;
    isHeritageSite = true;
    templeAreaInAcres = 2.5;
    deityName = "Lord Ganesha";
    hasGarden = true;
    noOfSteps = 10;
    architectureStyle = "Dravidian";
    hasParkingFacility = true;
    dailyVisitors = 1000;
    hasCanteen = true;
    mainFestival = "Ganesh Chaturthi";
    isOpenOnHolidays = true;
    noOfRoomsForPilgrims = 25;
    trustName = "Siddhivinayaka Trust";
    hasLibrary = false;
	
	    System.out.println("Temple Name: " + templeName);
        System.out.println("Location: " + location);
        System.out.println("Number of Pillars: " + noOfPillars);
        System.out.println("Number of Doors: " + noOfDoors);
        System.out.println("Number of Priests: " + noOfPriests);
        System.out.println("Year Established: " + yearEstablished);
        System.out.println("Is Heritage Site: " + isHeritageSite);
        System.out.println("Temple Area in Acres: " + templeAreaInAcres);
        System.out.println("Deity Name: " + deityName);
        System.out.println("Has Garden: " + hasGarden);
        System.out.println("Number of Steps: " + noOfSteps);
        System.out.println("Architecture Style: " + architectureStyle);
        System.out.println("Has Parking Facility: " + hasParkingFacility);
        System.out.println("Daily Visitors: " + dailyVisitors);
        System.out.println("Has Canteen: " + hasCanteen);
        System.out.println("Main Festival: " + mainFestival);
        System.out.println("Is Open on Holidays: " + isOpenOnHolidays);
        System.out.println("Number of Rooms for Pilgrims: " + noOfRoomsForPilgrims);
        System.out.println("Trust Name: " + trustName);
        System.out.println("Has Library: " + hasLibrary);
    }
}
